# MaxPool 2D

**Information**
$$ n_{H} = Matrix Height \tag{i}$$
$$ n_{W} = Matrix Weight \tag{ii}$$
$$ n_{C} = Matrix Channel \tag{iii}$$
$$ f = Filter Size \tag{iv}$$
$$ s = Stride \tag{v}$$


**Input Shape** 
$$ n_{H} * n_{W} * n_{C} \tag{1}$$

**Output Shape** 
$$ \left(\frac{n_{H}-f}{S}+1\right) * \left(\frac{n_{W}-f}{S}+1\right) * n_{C} \tag{2}$$

**Max Pooling**

$$
input
\left[
\begin{array}{ccc}
12&20&30&0\\
8&12&2&0\\
34&70&37&4\\
112&100&25&12\end{array}
\right]_{1x4x4x1}
\Rightarrow
filter
\left[
\begin{array}{ccc}
f&f\\
f&f\end{array}
\right]_{1x2x2x1}
\Rightarrow 
output
\left[
\begin{array}{ccc}
20&30\\
112&37\end{array}
\right]_{1x2x2x1}
$$




In [1]:
import warnings
warnings.filterwarnings("ignore")

## PyTorch

In [2]:
import torch

In [3]:
input = torch.tensor([[12,20,30,0],
            [8,12,2,0],
            [34,70,37,4],
            [112,100,25,12]])

input = input.float()
input

tensor([[ 12.,  20.,  30.,   0.],
        [  8.,  12.,   2.,   0.],
        [ 34.,  70.,  37.,   4.],
        [112., 100.,  25.,  12.]])

In [5]:
input = torch.tensor([[12,20,30,0],
            [8,12,2,0],
            [34,70,37,4],
            [112,100,25,12]])

input = input.float()
input = input.reshape([1,1,4,4])
input

tensor([[[[ 12.,  20.,  30.,   0.],
          [  8.,  12.,   2.,   0.],
          [ 34.,  70.,  37.,   4.],
          [112., 100.,  25.,  12.]]]])

In [6]:
# pool of square window of size=3, stride=2
m = torch.nn.MaxPool2d(kernel_size=2, stride=2)
output = m(input)
output

tensor([[[[ 20.,  30.],
          [112.,  37.]]]])

In [7]:
output.shape

torch.Size([1, 1, 2, 2])

## Tensorflow

In [8]:
import tensorflow as tf

In [9]:
x = tf.constant([[12,20,30,0],
            [8,12,2,0],
            [34,70,37,4],
            [112,100,25,12]])

x = input.float()

x = tf.reshape(x, [1,4,4,1])

# 1. Satır
# 2. Satır
# 3. Satır
# 4. Satır

x

<tf.Tensor: shape=(1, 4, 4, 1), dtype=float32, numpy=
array([[[[ 12.],
         [ 20.],
         [ 30.],
         [  0.]],

        [[  8.],
         [ 12.],
         [  2.],
         [  0.]],

        [[ 34.],
         [ 70.],
         [ 37.],
         [  4.]],

        [[112.],
         [100.],
         [ 25.],
         [ 12.]]]], dtype=float32)>

In [10]:
# data_format ile last_channel, first_channel düzenlenebiliyor.
max_pool_2d = tf.keras.layers.MaxPooling2D(pool_size=(2, 2), strides=(2, 2))

output = max_pool_2d(x)
output

<tf.Tensor: shape=(1, 2, 2, 1), dtype=float32, numpy=
array([[[[ 20.],
         [ 30.]],

        [[112.],
         [ 37.]]]], dtype=float32)>

In [11]:
output.shape

TensorShape([1, 2, 2, 1])